name: Test tunebook
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--frozen-lockfile]
      - run: pnpm lint
      - run: pnpm check
      - run: pnpm playwright install
      - run: pnpm test
